---
- name: Submit JCL from existing dataset
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  tasks:
    - name: Submit JCL from existing partitioned or sequential data set
      zos_job_submit:
        src: "{{IBMUSER.JCL(HELLO)}}'"
        remote_src: true
        location: DATA_SET
        wait_time: 60
        return_output: true
      register: job_output

    - name: Print raw job output safely
      ansible.builtin.debug:
        msg: 'Job {{ job_result.jobs[0].job_id }}'